# -*- coding: utf-8 -*-
"""STAGE 2 of the Ankur build — his 2026-10-07 "final cleanup" list.

Reads out-2026-10-07/ (stage 1 output of 2026-10-07-ankur-october-build.py) and writes
out-2026-10-07-final/. Chainable and idempotent: stage 1 may be re-run without losing this work.

ANKUR'S SIX ITEMS:
  1. Expense policy — attach as Side Letter Exhibit A (was a bracketed placeholder). The policy
     text is generated by 2026-09-18-expense-policy-generator.py and appended paragraph-by-
     paragraph so the Side Letter carries the actual document, not a reference to it.
  2. 83(b) — remove from the RSPA. His shares are fully vested, so they are not substantially
     nonvested property and no 83(b) election is applicable. §5.1 rewritten to say so and
     Schedule B deleted outright. Now consistent with Adviser Agreement §2.7.
  3. RSPA cleanup — exemption already finalised in stage 1 (Reg D 506(b) / §4(a)(2)); verified
     here, no brackets remain. Cap-table reconciliation added in full, see below.
  4. Charter + date — Side Letter date September → October. Subscription Agreement Exhibit A
     converted from a bracketed drafting instruction to a clean attachment cover page.
     ⚠️ The filed Certificate of Incorporation is NOT in the vault, so it cannot be inserted
     here. Norman must drop the PDF in before execution; the cover page now says so plainly
     instead of reading as a note to the drafter.
  5. Offering size / share mechanics — the Subscription Agreement now describes an offering of
     UP TO $1,500,000 at $2.025 per Share, no minimum aggregate raise, may close for less, no
     minimum individual subscription, officers/directors/affiliates may subscribe on the same
     terms (covers the $50K each from Norman and Sunjay), one or more closings. Removed: "a
     minimum allocation is $100,000", "approximately one percent (1.0%)", and "the offering
     comprises 15 such allocations ... representing 15% of the Company."
  6. Consequential, not on his list but required by item 5: the $1.5M/15% raise is no longer a
     fixed quantity, so every place that computed a post-Seed number from it is restated as
     illustrative with the formula that governs instead. Adviser Agreement §2.4 and RSPA
     Schedule A. Stage 1 already made §2.5 size-agnostic, which is what makes item 5 workable
     at all — had §2.5 still read "(the $1,500,000 / 15% raise)" it would now be wrong.

CAP TABLE RECONCILIATION — checked, and it ties exactly at the full raise:
      Founder   3,000,000 Class B              60.750%
      Sunjay      833,333 Class A              16.875%
      Ankur       166,667 + 30,864 = 197,531    4.000%
      Greg        166,667 Class A               3.375%
      Seed        740,741 Class A              15.000%
      TOTAL     4,938,272                     100.000%
  Pre-Seed FD 4,166,667; Ankur 166,667/4,166,667 = 4.0000%.
  $2.025/sh × 740,741 = $1,500,000.  4,000,000 / 0.81 = 4,938,272.
  ⚠️ The sent Subscription Agreement said 740,74**5** shares — a rounding error. Moot: that
  block is deleted by item 5.
  For a partial raise of $X: S = floor(X / 2.025); Ankur's post-Seed total = (4,000,000 + S) / 24.
"""
import copy
import sys
from pathlib import Path
from docx import Document
from docx.text.paragraph import Paragraph

HERE = Path(__file__).parent
SRC = HERE / "out-2026-10-07"
OUT = HERE / "out-2026-10-07-final"
OUT.mkdir(exist_ok=True)
POLICY = Path("/tmp/claude-0/-home-user-brain-vault/cdeb7b3c-9b38-5f86-b0fa-23ce6e519c4c"
              "/scratchpad/Cinderella Corp - Expense and Travel Policy (REVISED).docx")

FIRED = []


# ───────────────────────────── patch helpers ─────────────────────────────

def sub(doc, old, new, *, label, where=None):
    """Replace the first occurrence of `old` across runs. Asserts exactly one paragraph hit."""
    hits = 0
    for para in doc.paragraphs:
        if old not in para.text or (where and where not in para.text):
            continue
        runs, found = para.runs, False
        for i in range(len(runs)):
            acc = ""
            for j in range(i, len(runs)):
                acc += runs[j].text
                if old in acc:
                    head, _, tail = acc.partition(old)
                    runs[i].text = head + new + tail
                    for k in range(i + 1, j + 1):
                        runs[k].text = ""
                    found = True
                    break
            if found:
                break
        assert found, f"{label}: text present in paragraph but in no run span"
        hits += 1
        break
    assert hits == 1, f"{label}: expected 1 hit, got {hits}\n  needle: {old[:120]!r}"
    FIRED.append(label)


def find(doc, needle, *, label):
    for para in doc.paragraphs:
        if needle in para.text:
            return para
    raise AssertionError(f"{label}: paragraph not found: {needle[:90]!r}")


def drop(doc, needle, *, label):
    """Delete the paragraph containing `needle`."""
    para = find(doc, needle, label=label)
    para._p.getparent().remove(para._p)
    FIRED.append(label)


def insert_after(doc, anchor, lead, body, *, label):
    """Clone the paragraph containing `anchor` and insert a new one directly after it."""
    src = find(doc, anchor, label=label)
    new_p = copy.deepcopy(src._p)
    src._p.addnext(new_p)
    np = Paragraph(new_p, src._parent)
    assert np.runs, f"{label}: clone has no runs"
    if len(np.runs) == 1:
        # anchor is a single-run paragraph; clone its run so the lead can be bolded separately
        np.runs[0]._r.addnext(copy.deepcopy(np.runs[0]._r))
    np.runs[0].text = lead
    np.runs[0].bold = True
    np.runs[1].text = body
    np.runs[1].bold = False
    for r in np.runs[2:]:
        r.text = ""
    FIRED.append(label)
    return np


def append_doc_after(doc, anchor, policy_path, *, label, skip=0):
    """Append every paragraph of `policy_path` after the paragraph containing `anchor`,
    carrying its own formatting across (deep copy of the source XML)."""
    src = find(doc, anchor, label=label)
    cursor = src._p
    n = 0
    for p in Document(policy_path).paragraphs[skip:]:
        clone = copy.deepcopy(p._p)
        cursor.addnext(clone)
        cursor = clone
        n += 1
    assert n > 20, f"{label}: only {n} paragraphs appended, expected the full policy"
    FIRED.append(f"{label} ({n} paras)")
    return n


# ═══════════════════════ 1. RSPA — ANKUR: 83(b) OUT, MATH IN ═══════════════════════

d = Document(SRC / "Cinderella_Corp_-_RSPA_-_Ankur_Jain.docx")

sub(d,
    "83(b) election.",
    "No 83(b) election applicable.",
    label="RSPA §5.1 heading", where="5. TAX")

sub(d,
    "Purchaser is strongly advised to consult his or her own tax adviser and to consider filing "
    "an election under Section 83(b) of the Internal Revenue Code within thirty (30) days of the "
    "Effective Date. The election is Purchaser’s sole responsibility; the Company makes no tax "
    "representation and has no obligation to file it on Purchaser’s behalf. A form of election "
    "is attached as Schedule B.",
    "The Shares are fully vested as of the Effective Date and are not subject to any repurchase "
    "option for unvested shares. The Shares are accordingly not substantially nonvested property "
    "within the meaning of Section 83 of the Internal Revenue Code, and no election under "
    "Section 83(b) of the Code is applicable to or required in respect of the Shares. This is "
    "consistent with Section 2.7 of Purchaser’s Strategic Adviser Agreement. Purchaser "
    "remains responsible for his own tax position and is advised to consult his own tax adviser; "
    "the Company makes no tax representation.",
    label="RSPA §5.1 body")

drop(d, "[Attach the standard Internal Revenue Code Section 83(b) election form.",
     label="RSPA Schedule B body deleted")
drop(d, "SCHEDULE B — FORM OF 83(b) ELECTION",
     label="RSPA Schedule B heading deleted")

sub(d,
    "4.000% of the fully-diluted capitalization as of the Effective Date (pre-Seed fully- "
    "diluted total: 4,166,667 shares)",
    "4.000% of the fully-diluted capitalization as of the Effective Date. The pre-Seed "
    "fully-diluted total is 4,166,667 shares, comprising 3,000,000 shares of Class B Common "
    "Stock held by the Founder, 833,333 shares of Class A Common Stock held by Sunjay Mathews, "
    "the 166,667 Shares issued hereunder, and 166,667 shares of Class A Common Stock held by one "
    "further adviser. 166,667 ÷ 4,166,667 = 4.0000%.",
    label="RSPA Schedule A — pre-Seed reconciliation")

sub(d,
    "Based on current capitalization the top-up is expected to be approximately 30,864 shares, "
    "for a post-Seed total of approximately 197,531 shares of a 4,938,272-share fully-diluted "
    "total. The top-up shares are fully vested on issuance and are treated as Shares under this "
    "Agreement. Actual numbers are those required to produce 4% and are subject to rounding.",
    "The top-up shares are fully vested on issuance and are treated as Shares under this "
    "Agreement. The actual number is whatever is required to produce 4%, and is subject to "
    "rounding. ILLUSTRATION ONLY — the Seed Round is an offering of up to $1,500,000 of Class A "
    "Common Stock at $2.025 per share with no minimum aggregate raise, so the figures below "
    "assume the full amount is sold and will differ if less is sold. On that assumption the Seed "
    "Round issues 740,741 shares for $1,500,000; the top-up is 30,864 shares, bringing Purchaser "
    "to 197,531 shares of a 4,938,272-share fully-diluted total (4.000%); and the post-Seed "
    "capitalization is Founder 3,000,000 (60.750%), Sunjay Mathews 833,333 (16.875%), Purchaser "
    "197,531 (4.000%), the further adviser 166,667 (3.375%) and the Seed Round 740,741 "
    "(15.000%), totalling 4,938,272 shares and 100.000%. For a Seed Round of $X, the shares sold "
    "are X ÷ $2.025 rounded down to a whole share (S), and Purchaser’s post-Seed total is "
    "(4,000,000 + S) ÷ 24.",
    label="RSPA Schedule A — top-up reconciliation")

d.save(OUT / "Cinderella_Corp_-_RSPA_-_Ankur_Jain.docx")


# ═══════════════════ 2. ADVISER AGREEMENT — same illustration caveat ═══════════════════

d = Document(SRC / "Ankur_Jain_Strategic_Adviser_Agreement.docx")

sub(d,
    "Based on the Company’s capitalization as of the date of this Agreement, the parties "
    "expect the Role Shares to be 166,667 shares and the Top-Up Shares to be approximately "
    "30,864 shares, for a post-Seed total of approximately 197,531 shares; the actual numbers "
    "are those required to produce four percent (4%) and are subject to rounding.",
    "Based on the Company’s capitalization as of the date of this Agreement, the Role Shares "
    "are 166,667 shares of a 4,166,667-share fully-diluted total. The Seed Round is an offering "
    "of up to $1,500,000 of Class A Common Stock at $2.025 per share with no minimum aggregate "
    "raise, and may close for less than the full amount; the Top-Up Shares therefore cannot be "
    "fixed in advance. Were the full amount sold, the Top-Up Shares would be approximately "
    "30,864, for a post-Seed total of approximately 197,531 shares of a 4,938,272-share "
    "fully-diluted total. That figure is an illustration only. The actual number of Top-Up "
    "Shares is whatever is required to produce four percent (4%) of the fully-diluted "
    "capitalization immediately following the closing of the Seed Round, whatever its final "
    "size, and is subject to rounding.",
    label="Adviser §2.4 — top-up illustration")

d.save(OUT / "Ankur_Jain_Strategic_Adviser_Agreement.docx")


# ═════════════ 3. SIDE LETTER — October date + Expense Policy actually attached ═════════════

d = Document(SRC / "Cinderella_Corp_-_Side_Letter_Agreement_Revenue_Share_Final.docx")

sub(d, "as of September [ ], 2026", "as of October [ ], 2026", label="Side Letter date → October")

append_doc_after(d, "EXPENSE & TRAVEL POLICY",
                 POLICY, label="Side Letter Exhibit A — policy attached", skip=1)
drop(d, "[Attached the Expense & Travel Policy adopted by the Company.]",
     label="Side Letter Exhibit A placeholder removed")

d.save(OUT / "Cinderella_Corp_-_Side_Letter_Agreement_Revenue_Share_Final.docx")


# ═════════════ 4. SUBSCRIPTION AGREEMENT — offering mechanics + charter cover ═════════════

d = Document(SRC / "Cinderella_Corp_-_Subscription_Agreement_Final.docx")

insert_after(d,
             "The Investor hereby irrevocably subscribes for that number of Shares set forth on "
             "the signature page",
             "Offering; no minimum.  ",
             "The Company is offering up to One Million Five Hundred Thousand Dollars "
             "($1,500,000) of Shares at the price of $2.025 per Share. There is no minimum "
             "aggregate amount that must be subscribed, and the Company may accept subscriptions "
             "for, and complete the offering at, any amount less than $1,500,000. There is no "
             "minimum and no maximum individual subscription amount; subscription amounts may "
             "vary among Investors, and the Company’s officers, directors, employees and "
             "affiliates may subscribe on the same terms as any other Investor. The Company may "
             "accept or reject any subscription in whole or in part in its sole discretion, and "
             "may conduct the offering in one or more closings. The number of Shares the Investor "
             "purchases is the Investor’s subscription amount divided by $2.025 per Share, "
             "rounded down to the nearest whole Share; no fractional Shares will be issued. The "
             "Investor’s percentage ownership of the Company is determined solely by the "
             "number of Shares purchased relative to the Company’s fully-diluted "
             "capitalization as of the final closing of the offering, and the Company makes no "
             "representation that any subscription amount corresponds to any particular "
             "percentage of the Company.",
             label="Subscription — Offering clause inserted")

sub(d,
    "A minimum allocation is $100,000, being 49,383 Shares at $2.025 per Share and representing "
    "approximately one percent (1.0%) of the Company on a fully-diluted basis immediately "
    "following the closing of the offering. The offering comprises 15 such allocations, being "
    "740,745 Shares in the aggregate for $1,500,000, representing 15% of the Company.",
    "Number of Shares equals the Subscription Amount divided by $2.025 per Share, rounded down "
    "to the nearest whole Share. The Company is offering up to $1,500,000 of Shares at that "
    "price. There is no minimum aggregate raise and no minimum individual subscription, and the "
    "offering may close for less than the full amount. Percentage ownership is determined by the "
    "Shares actually purchased and the Company’s fully-diluted capitalization at the final "
    "closing of the offering.",
    label="Subscription — allocation block replaced")

sub(d,
    "[Attach the Amended and Restated Certificate of Incorporation of Cinderella Corp., as "
    "amended to date, authorizing 6,000,000 shares of Class A Common Stock and 4,000,000 shares "
    "of Class B Common Stock and no preferred stock.]",
    "The Certificate of Incorporation of Cinderella Corp., as amended to date and as filed with "
    "the Secretary of State of the State of Delaware — authorizing 6,000,000 shares of Class "
    "A Common Stock and 4,000,000 shares of Class B Common Stock, and no preferred stock — "
    "follows this page.",
    label="Subscription Exhibit A — charter cover page")

d.save(OUT / "Cinderella_Corp_-_Subscription_Agreement_Final.docx")


# ════════════════════ 5. STOCKHOLDERS' AGREEMENT — pass through unchanged ════════════════════

d = Document(SRC / "Cinderella_Corp_-_Stockholders_Agreement_-_Ankur_Jain.docx")
d.save(OUT / "Cinderella_Corp_-_Stockholders_Agreement_-_Ankur_Jain.docx")


# ══════════════════ 6. VERSION NOTE — all five, so copies are distinguishable ══════════════════

NOTE = ("Revised 2026-10-07 (final) — incorporating Adviser’s 2026-10-07 comments and his "
        "final cleanup list; supersedes all earlier 2026-10-07 copies.")
for f in sorted(OUT.glob("*.docx")):
    doc = Document(f)
    hit = next(((i, p) for i, p in enumerate(doc.paragraphs[:5])
                if "Revised 2026-10-07" in p.text or "incorporating Adviser" in p.text), None)
    assert hit, f"version note: no stage-1 note in the first 5 paragraphs of {f.name}"
    i, p = hit
    p.runs[0].text = NOTE
    for r in p.runs[1:]:
        r.text = ""
    doc.save(f)
    FIRED.append(f"version note — {f.name[:34]}")


# ════════════════════════════════ VERIFICATION ════════════════════════════════

print(f"{len(FIRED)} changes applied:")
for f in FIRED:
    print("  ✓", f)

checks = {
    "Cinderella_Corp_-_RSPA_-_Ankur_Jain.docx": [
        ("No 83(b) election applicable", True),
        ("not substantially nonvested property", True),
        ("consider filing an election under Section 83(b)", False),
        ("SCHEDULE B", False),
        ("Schedule B", False),
        ("166,667 ÷ 4,166,667 = 4.0000%", True),
        ("totalling 4,938,272 shares and 100.000%", True),
        ("Regulation D", True),
        ("[Rule 701", False),
        ("[FMV as determined by the Board]", False),
        ("740,745", False),
    ],
    "Ankur_Jain_Strategic_Adviser_Agreement.docx": [
        ("up to $1,500,000 of Class A Common Stock at $2.025 per share", True),
        ("an illustration only", True),
        ("whatever its final size, price and structure", True),   # stage-1 §2.5 survives
        ("the $1,500,000 / 15% raise", False),
    ],
    "Cinderella_Corp_-_Side_Letter_Agreement_Revenue_Share_Final.docx": [
        ("as of October [ ], 2026", True),
        ("September [ ], 2026", False),
        ("[Attached the Expense & Travel Policy", False),
        ("Maximum lodging rate: $300 per night", True),
        ("No person may approve his or her own exception", True),
        ("1.  Purpose and Scope", True),
    ],
    "Cinderella_Corp_-_Subscription_Agreement_Final.docx": [
        ("Offering; no minimum.", True),
        ("no minimum aggregate amount that must be subscribed", True),
        ("may conduct the offering in one or more closings", True),
        ("officers, directors, employees and affiliates may subscribe", True),
        ("A minimum allocation is $100,000", False),
        ("approximately one percent", False),
        ("15 such allocations", False),
        ("740,745", False),
        ("follows this page", True),
        ("[Attach the Amended and Restated Certificate", False),
    ],
}
print("\nverification:")
bad = 0
for fname, cs in checks.items():
    t = "\n".join(p.text for p in Document(OUT / fname).paragraphs)
    for needle, want in cs:
        ok = (needle in t) is want
        bad += not ok
        print(f"  {'OK  ' if ok else 'FAIL'} {fname[:40]:<42} {'has' if want else 'no ':<3} {needle[:50]!r}")

# the Stockholders' Agreement must still match Sunjay's and Greg's conformed copies
import re
def clause(path, key):
    for p in Document(path).paragraphs:
        if p.text.strip().startswith(key):
            return re.sub(r"\s+", " ", p.text).strip()
sg = HERE / "out-sunjay-greg-2026-10-07"
for key in ("2.6", "2.7"):
    a = clause(OUT / "Cinderella_Corp_-_Stockholders_Agreement_-_Ankur_Jain.docx", key)
    s = clause(sg / "Cinderella_Corp_-_Stockholders_Agreement_-_Sunjay_Mathews.docx", key)
    g = clause(sg / "Cinderella_Corp_-_Stockholders_Agreement_-_Greg_Kristof.docx", key)
    ok = a == s == g
    bad += not ok
    print(f"  {'OK  ' if ok else 'FAIL'} SHA §{key} still identical across all three holders")

print(f"\n{'ALL CHECKS PASSED' if not bad else f'{bad} CHECK(S) FAILED'}")
sys.exit(1 if bad else 0)
